### ISSUE TITLE
About the Proof of Theorem1

### ISSUE THREAD

**Issue by YangPatrick** [YyzHarry/imbalanced-semi-self#11]
At the end of proof, the probability of event E is 1-P1-P2-P3 
BUT WHY not the product of three probability which is (1-P1)(1-P2)(1-P3)?

**Comment by YyzHarry** [comment]
Hi - here we are using the union bound to derive the lower bound. This does not assume whether the events are independent or not.

**Comment by YangPatrick** [comment]
Thanks for your response. 
There is another question is about theoretical motivation in self-supervision. You assume the major class is negative and negative samples have larger variance. Are thes two events relevent or just assumption?
In visualization, class with more samples seems to have larger variance, but i think the true distribution is not related to the number of samples.

**Comment by YyzHarry** [comment]
These are just assumptions for the toy model, and are not necessarily relevent.
