### ISSUE TITLE
请教大大一个问题：FileNotFoundError: [Errno 2] No such file or directory: './data/ti_80M_selected.pickle'

### ISSUE THREAD

**Issue by mechsihao** [YyzHarry/imbalanced-semi-self#13]
作者大大你好，想请教下，我看论文里整个self-training阶段的总loss为：
![image](https://user-images.githubusercontent.com/46416241/105275754-f537b900-5bda-11eb-9213-5e086699a222.png)
那这个 **\omega** 是怎么定的呢？还有半监督学习的总轮数epoch的确定方法。

**Comment by YyzHarry** [comment]
Hi - thank you for your interest!

- For `ti_80M_selected.pickle`, you can find the file [here](https://drive.google.com/file/d/1SODQBUvv2qycDivBb4nhHaCk3TMzaVM4/view?usp=sharing). The link is also provided in the README.
- `\omega`: We simply use 1 for all experiments. It's possible that a better selected `\omega` can lead to better results. As for the epoch number, it is the same as the one without unlabeled data (you can refer to our code, e.g., [`train_semi.py`](https://github.com/YyzHarry/imbalanced-semi-self/blob/master/train_semi.py)).
