### ISSUE TITLE
The pretrained models of "self" can not be open,can you solve it,pealse?

### ISSUE THREAD

**Issue by NARRZ** [YyzHarry/imbalanced-semi-self#15]

**Comment by YyzHarry** [comment]
Hi - I double check the checkpoints, and I can load them correctly. What problem did you experience? Did you follow the provided scripts? For example: https://github.com/YyzHarry/imbalanced-semi-self/blob/master/train.py#L157-L162

**Comment by NARRZ** [comment]
Thanks for you apply,but I mean that I can't download the pretrained models of "self" from https://drive.google.com/drive/folders/1VbdqYZ0sqyApM6AdmCgsZd46TsPlQcpT.  Files downloaded in "self" folder cannot be unzipped.Please verify it when you are spare.

**Comment by YyzHarry** [comment]
I can download and load the checkpoints. FYI, you do not need to unzip the checkpoints; the files are meant to be directly loaded. Check out the [PyTorch saving and loading procedure](https://pytorch.org/tutorials/beginner/saving_loading_models.html).
