### ISSUE TITLE
command to get a base classifier in semi-supervised learning

### ISSUE THREAD

**Issue by abababa-ai** [YyzHarry/imbalanced-semi-self#20]
In semi-supervised training, what is the command to get the base classifier using only labeled data?

**Comment by YyzHarry** [comment]
Hi - thanks for your interest. The base model is obtained by normal training procedure on the labeled imbalanced dataset. You can also customize the base loss function or training procedure for the base classifier. For example, with `CE`, `\rho=100` on CIFAR-10:
```python
python train.py --dataset cifar10 --imb_factor 0.01 --loss_type CE
```
Or with `LDAM`:
```python
python train.py --dataset cifar10 --imb_factor 0.01 --loss_type LDAM
```
