### ISSUE TITLE
error python pretrain_rot.py --dataset cifar10 --imb_factor 0.01

### ISSUE THREAD

**Issue by madoka109** [YyzHarry/imbalanced-semi-self#22]
When I use python pretrain_rot.py --dataset cifar10 --imb_factor 0.01,it occurs RuntimeError: Given input size: (2048x1x1). Calculated output size: (2048x0x0). Output size is too small.
How should I modify the code?

**Comment by YyzHarry** [comment]
Hi - did you modify the network architecture? For CIFAR experiments, one should use `resnet32` as default architecture.

**Comment by madoka109** [comment]
I understand, thank you very much. 
Besides, I have another question. I know the epochs of **Network training with SSP models** is 200. But the epochs of pretrained model is 200 or the other? 
And when I try to use 200 epochs to get pretrained model,  I directly get the result 83.750, it seems better than the results of the paper. Do I misunderstand something? 
![图片](https://user-images.githubusercontent.com/79368885/133191703-149b3934-3c40-4979-94d2-68a05397c6da.png)

**Comment by YyzHarry** [comment]
I assume this accuracy is for the self-supervised pre-training task --- that is classifying rotation in this case. So it is different from the actual imbalanced classification performance.

**Comment by madoka109** [comment]
I understand, thank you!
