### ISSUE TITLE
How to get the image in the readme

### ISSUE THREAD

**Issue by 87nohigher** [YyzHarry/imbalanced-semi-self#23]
Could you give some hint how to get the image stored in the directory of assets?
I want to get that type of image on my own dataset.
Thanks
![tsne_self](https://user-images.githubusercontent.com/52370816/139578797-05501efa-da38-4674-9feb-ceafe09ac5c7.png)

**Comment by YyzHarry** [comment]
Hi - As stated in our paper, the figure is generated using [t-SNE](https://lvdmaaten.github.io/tsne/) projection of the learnt representations. You can first save the features and then run t-SNE on them. We used the [tsne function in the sklearn library](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html) for implementation.

**Comment by 87nohigher** [comment]
Thanks for your reply.
Could you release the code of the implementation?
Thanks a lot

**Comment by YyzHarry** [comment]
Unfortunately I didn't save the visualization as a single file, but it should be simple and straightforward to implement: save the features first, and then run [t-SNE](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html) on them.

**Comment by 87nohigher** [comment]
Thanks, I have implemented it successfully.
