### ISSUE TITLE
Error:  No module named 'dataset.resnet_cifar' when running

### ISSUE THREAD

**Issue by khuongnd** [YyzHarry/imbalanced-semi-self#3]
When I run this command:
python train_semi.py --dataset cifar10 --imb_factor 0.02 --imb_factor_unlabel 0.02

I got this error:
Traceback (most recent call last):
  File "train_semi.py", line 15, in <module>
    from dataset.imbalance_cifar import SemiSupervisedImbalanceCIFAR10
  File "/home/insights-user/imbalanced-semi-self/dataset/__init__.py", line 1, in <module>
    from .resnet_cifar import *
ModuleNotFoundError: No module named 'dataset.resnet_cifar'

**Comment by YyzHarry** [comment]
Can you please double check you have the right code/structure as in this repo? Since there's no `dataset/init.py` in the provided code.
