### ISSUE TITLE
Category imbalance

### ISSUE THREAD

**Issue by lyc1995452-star** [YyzHarry/imbalanced-semi-self#4]
I'm going to do semantic segmentation of deeplabv3+, but I have a problen with Category imbalance. Please help me to solve this problem. Thanks

**Comment by YyzHarry** [comment]
Hi --- Your problem seems independent of the techniques or code provided in this repo. I'm closing this issue. Feel free to add comments if you have problems running code / reproducing the results / applying our techniques, or have related questions on our paper.
