### ISSUE TITLE
训练自己数据集

### ISSUE THREAD

**Issue by shenyingying** [YyzHarry/imbalanced-semi-self#6]
非常感谢作者作出的贡献，如果能给出训练自己数据集的具体步骤就更好了。

**Comment by YyzHarry** [comment]
Hi, thank you for your interest. To apply on your own datasets:

- __Semi-supervised__: You just need to first collect (relevant) unlabeled data. As indicated by our results, as long as the data relevance is high, even the unlabeled data is also (highly) imbalanced, it can still (almost always) improve the imbalanced learning results. Then you can just use self-training, or other semi-supervised techniques (advanced methods such as VAT/MT will achieve better results, see our Appendix E.1).
- __Self-supervised__: Depending on your data format, you can choose any self-supervised learning methods that are suitable for your own data. All you need is to first do self-supervised pre-training without using imbalanced labels. Then you can use any base training method to do supervised training. As our paper shows, it can consistently improve the results, regardless of the base training techniques.

**Comment by SparkParis** [comment]
please give me a detail to train my databases

**Comment by SparkParis** [comment]
thank you

**Comment by ShirleyHe2020** [comment]
Love your idea .Can you plz share more details about how to train custom datasets?

**Comment by YyzHarry** [comment]
Hi @SparkParis @ShirleyHe2020  - thanks for your interest! General details are indicated as above:

- __Semi-supervised__: You just need to first collect (relevant) unlabeled data. As indicated by our results, as long as the data relevance is high, even the unlabeled data is also (highly) imbalanced, it can still (almost always) improve the imbalanced learning results. Then you can just use self-training, or other semi-supervised techniques (advanced methods such as VAT/MT will achieve better results, see our Appendix E.1).
- __Self-supervised__: Depending on your data format, you can choose any self-supervised learning methods that are suitable for your own data. All you need is to first do self-supervised pre-training without using imbalanced labels. Then you can use any base training method to do supervised training. As our paper shows, it can consistently improve the results, regardless of the base training techniques.

Let me know if you have any questions.
